

export const stateUnemploymentLinks: Record<string, string> = {
    'Alabama': 'https://labor.alabama.gov/uc/claimants.aspx',
    'Alaska': 'https://labor.alaska.gov/unemployment/',
    'Arizona': 'https://des.az.gov/services/employment/unemployment-individual',
    'Arkansas': 'https://www.dws.arkansas.gov/unemployment/',
    'California': 'https://edd.ca.gov/en/unemployment/',
    'Colorado': 'https://cdle.colorado.gov/unemployment',
    'Connecticut': 'https://www.ctdol.state.ct.us/progsupt/unemplt/unemployment.htm',
    'Delaware': 'https://ui.delawareworks.com/',
    'Florida': 'https://www.floridajobs.org/Reemployment-Assistance-Service-Center/reemployment-assistance/claimants',
    'Georgia': 'https://dol.georgia.gov/individuals/unemployment-benefits',
    'Hawaii': 'https://labor.hawaii.gov/ui/',
    'Idaho': 'https://www.labor.idaho.gov/dnn/Unemployment-Benefits',
    'Illinois': 'https://ides.illinois.gov/unemployment.html',
    'Indiana': 'https://www.in.gov/dwd/indiana-unemployment/',
    'Iowa': 'https://www.iowaworkforcedevelopment.gov/unemployment-insurance-services',
    'Kansas': 'https://www.getkansasbenefits.gov/',
    'Kentucky': 'https://kcc.ky.gov/Pages/default.aspx',
    'Louisiana': 'https://www.laworks.net/unstuff/unemployment_insurance.asp',
    'Maine': 'https://www.maine.gov/unemployment/',
    'Maryland': 'https://www.dllr.state.md.us/employment/unemployment.shtml',
    'Massachusetts': 'https://www.mass.gov/topics/unemployment-information',
    'Michigan': 'https://www.michigan.gov/leo/bureaus-agencies/uia',
    'Minnesota': 'https://www.uimn.org/',
    'Mississippi': 'https://mdes.ms.gov/unemployment-claims/',
    'Missouri': 'https://labor.mo.gov/unemployed-workers',
    'Montana': 'https://uid.dli.mt.gov/claimants/',
    'Nebraska': 'https://dol.nebraska.gov/uibenefits',
    'Nevada': 'https://ui.nv.gov/css.html',
    'New Hampshire': 'https://www.nhes.nh.gov/',
    'New Jersey': 'https://www.myunemployment.nj.gov/',
    'New Mexico': 'https://www.dws.state.nm.us/unemployment',
    'New York': 'https://dol.ny.gov/unemployment',
    'North Carolina': 'https://des.nc.gov/',
    'North Dakota': 'https://www.jobsnd.com/unemployment',
    'Ohio': 'https://jfs.ohio.gov/job-services-and-unemployment/unemployment',
    'Oklahoma': 'https://oklahoma.gov/oesc.html',
    'Oregon': 'https://unemployment.oregon.gov/',
    'Pennsylvania': 'https://www.uc.pa.gov/',
    'Rhode Island': 'https://dlt.ri.gov/ui/',
    'South Carolina': 'https://dew.sc.gov/',
    'South Dakota': 'https://dlr.sd.gov/ra/default.aspx',
    'Tennessee': 'https://www.tn.gov/workforce/unemployment.html',
    'Texas': 'https://www.twc.texas.gov/jobseekers/unemployment-benefits-services',
    'Utah': 'https://jobs.utah.gov/ui/home',
    'Vermont': 'https://labor.vermont.gov/unemployment-insurance',
    'Virginia': 'https://www.vec.virginia.gov/',
    'Washington': 'https://esd.wa.gov/unemployment',
    'West Virginia': 'https://workforcewv.org/unemployment',
    'Wisconsin': 'https://dwd.wisconsin.gov/uiben/ claimants.htm',
    'Wyoming': 'https://dws.wyo.gov/dws-services/unemployment-insurance/',
};
